In [8]:
pip install scikit-multilearn


Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Using cached scikit_multilearn-0.2.0-py3-none-any.whl.metadata (6.0 kB)
Using cached scikit_multilearn-0.2.0-py3-none-any.whl (89 kB)


In [54]:
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.datasets import make_multilabel_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from scipy.sparse import csr_matrix
import numpy as np
from scipy.sparse import csr_matrix

In [68]:
X, y = make_multilabel_classification(n_samples=1000, n_classes=5, n_labels=3, random_state=42)

classifier = BinaryRelevance(classifier=RandomForestClassifier(), require_dense=[False,True])

classifier.fit(X, y)

new_instance = [[1, 2, 3, 4, 5,1,2,3,4,5,1,2,3,4,5,1,2,3,4,5], [6, 7, 8, 9, 10,6,7,8,9,10,6,7,8,9,10,6,7,8,9,10]]
predictions = classifier.predict(new_instance)
dense_predictions = predictions.toarray()
dense_predictions
# y

array([[1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0],
       ...,
       [1, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_multilabel_classification
from scipy.sparse import csr_matrix
from skmultilearn.problem_transform import BinaryRelevance

classes = ['science', 'sports', 'mathematics']

new_instance = [
    ['geography', 'statistics', 'calculus', 'geography', 'statistics', 'calculus', 'geography', 'statistics', 'calculus', 'geography', 'statistics', 'calculus', 'geography', 'statistics', 'calculus', 'geography', 'statistics', 'calculus', 'geography', 'statistics'],  
    ['sports', 'mathematics', 'statistics', 'sports', 'mathematics', 'statistics', 'sports', 'mathematics', 'statistics', 'sports', 'mathematics', 'statistics', 'sports', 'mathematics', 'statistics', 'sports', 'mathematics', 'statistics', 'sports', 'mathematics']   
]

binary_representation = []

for instance in new_instance:
    binary_vector = [1 if cls in instance else 0 for cls in classes]
    binary_representation.append(binary_vector)
new_instance_csr = csr_matrix(binary_representation)


classifier = BinaryRelevance(classifier=RandomForestClassifier(), require_dense=[False, True])
classifier.fit(new_instance, y)

predictions = classifier.predict(new_instance_csr)

print(predictions.toarray())


TypeError: no supported conversion for types: (dtype('<U11'),)

In [65]:
from sklearn.datasets import make_multilabel_classification

# Generate synthetic data with 1000 samples, 20 features, 5 classes, and 3 labels per instance
X, y = make_multilabel_classification(n_samples=1000, n_features=20, n_classes=5, n_labels=3, random_state=42)

# Print the shape of X and y
print("Shape of X:", X.shape)  # Should be (1000, 20)
print("Shape of y:", y.shape)  # Should be (1000, 5)

# Display the first 5 rows of X and y
print("First 5 samples of X:\n", X[:5])
print("First 5 samples of y:\n", y[:5])


Shape of X: (1000, 20)
Shape of y: (1000, 5)
First 5 samples of X:
 [[2. 3. 1. 2. 3. 6. 4. 5. 1. 5. 3. 0. 2. 3. 3. 1. 5. 4. 1. 3.]
 [2. 4. 2. 0. 3. 1. 1. 2. 0. 0. 1. 3. 1. 7. 2. 2. 2. 7. 1. 0.]
 [0. 3. 1. 1. 2. 0. 0. 3. 1. 4. 0. 0. 2. 3. 4. 2. 5. 6. 4. 7.]
 [6. 3. 1. 4. 0. 4. 0. 1. 3. 7. 0. 2. 5. 3. 3. 2. 2. 2. 0. 2.]
 [2. 1. 2. 1. 0. 0. 4. 1. 3. 1. 1. 0. 1. 0. 1. 5. 5. 5. 1. 3.]]
First 5 samples of y:
 [[1 1 0 1 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [75]:
from sklearn.naive_bayes import MultinomialNB
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import csr_matrix

# Define the school subjects
subjects = ['mathematics', 'science', 'history', 'geography', 'literature']

# Define the new instances (sets of school subjects)
new_instances = [
    ['mathematics', 'science'],  
    ['history', 'geography', 'literature']   
]

# Convert the sets of school subjects into text documents
# This step is necessary for text-based classifiers like Multinomial Naive Bayes
text_documents = [' '.join(instance) for instance in new_instances]

# Initialize the CountVectorizer to convert text into a matrix of token counts
vectorizer = CountVectorizer(vocabulary=subjects)
# vectorizer

# # Transform the text documents into a document-term matrix
X_new = vectorizer.transform(text_documents)

# Define the true labels (not necessary for prediction, just for demonstration)
y_true = [
    [1, 1, 0, 0, 0],  # 'mathematics' and 'science'
    [0, 0, 1, 1, 1]   # 'history', 'geography', and 'literature'
]

# Convert the true labels into a CSR matrix
y_true_csr = csr_matrix(y_true)

# Initialize the Binary Relevance classifier with Multinomial Naive Bayes as the base classifier
classifier = BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])

# Fit the classifier to the training data
classifier.fit(X_new, y_true_csr)

# Predict the labels for the new instances
predictions = classifier.predict(X_new)

# Print the predicted labels
print("Predicted Labels:")
print(predictions.toarray())


Predicted Labels:
[[1 1 0 0 0]
 [0 0 1 1 1]]


In [77]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_new, y_true_csr, test_size=0.2, random_state=42)

# Initialize the Binary Relevance classifier with Multinomial Naive Bayes as the base classifier
classifier = BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])

# Fit the classifier to the training data
classifier.fit(X_train, y_train)

# Predict the labels for the testing set
predictions = classifier.predict(X_test)

# Print the predicted labels for the testing set
print("Predicted Labels for Testing Set:")
print(predictions.toarray())

# Evaluate the performance of the model (e.g., accuracy, precision, recall, etc.)
# You can use appropriate metrics to evaluate the model's performance on the testing set


Predicted Labels for Testing Set:
[[1 1 0 0 0]]
